name = "hotbeam-contact"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[send_email]]
name = "SEND_EMAIL"
destination_address = "contact@hotbeamproductions.com"
