name = "hotbeam-contact"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ALLOWED_ORIGINS = "https://hotbeamproductions.com,https://www.hotbeamproductions.com,https://hotbeam.hot-beam-productions.workers.dev,http://localhost:3000"
CONTACT_TO_ADDRESS = "contact@hotbeamproductions.com"

[[send_email]]
name = "SEND_EMAIL"
destination_address = "contact@hotbeamproductions.com"
